name: Vi Commands
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: read

jobs:
  apply-command:
    if: startsWith(github.event.comment.body, '/vi ')
    runs-on: ubuntu-latest
    steps:
      - name: Check actor is allowed
        id: auth
        run: |
          ALLOWED="${{ github.repository_owner }}"
          if [ "${{ github.actor }}" != "$ALLOWED" ]; then
            echo "Only the repo owner can run /vi commands."
            exit 1
          fi

      - uses: actions/checkout@v4

      - name: Parse command
        id: parse
        shell: bash
        run: |
          BODY=$(cat <<'EOF'
          ${{ github.event.comment.body }}
          EOF
          )
          # first line: /vi commit <file_path>
          LINE1=$(echo "$BODY" | head -n1)
          CMD=$(echo "$LINE1" | awk '{print $2}')
          FILE=$(echo "$LINE1" | awk '{print $3}')
          # extract first fenced code block content
          CONTENT=$(echo "$BODY" | awk 'f;/^```/{f^=1;next}')
          # drop language line if present
          CONTENT=$(echo "$CONTENT" | sed '1{/^```/d}')
          # remove trailing closing fence if present
          CONTENT=$(echo "$CONTENT" | sed '/^```$/d')
          if [ -z "$CMD" ] || [ -z "$FILE" ]; then
            echo "Missing command or file path"; exit 1; fi
          echo "cmd=$CMD" >> $GITHUB_OUTPUT
          echo "file=$FILE" >> $GITHUB_OUTPUT
          printf "%s" "$CONTENT" > _vi_payload.txt

      - name: Apply /vi commit
        if: steps.parse.outputs.cmd == 'commit'
        run: |
          FILE="${{ steps.parse.outputs.file }}"
          mkdir -p "$(dirname "$FILE")"
          mv _vi_payload.txt "$FILE"
          git config user.name "vi-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "vi: update $FILE via issue comment" || echo "No changes to commit."
          git push
